import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fixture } from './fixtures.js';
import { Engine, prepare, catalog, capcutState } from '../lib/engine.js';
import { loadProject } from '../lib/projects.js';
import { readJson } from '../lib/storage.js';
const withFixture=(options,fn)=>{const f=fixture(options);try{return fn(f)}finally{f.cleanup()}};
const engine=f=>new Engine({root:f.root,backupDir:f.backupDir,guard:()=>{}});
const error=(fn,code)=>assert.throws(fn,e=>e.code===code);

test('aperçu sans écriture et generation avec voix off',()=>withFixture({},f=>{
  const before=fs.readFileSync(f.draftFile);const e=engine(f),r=e.preview(f.project,{});assert.equal(r.scenes,2);assert(fs.readFileSync(f.draftFile).equals(before));
  const committed=e.commit(r.token);assert.equal(committed.files,3);const draft=readJson(f.draftFile).value;assert.equal(draft.duration,30000000);assert.equal(draft.tracks.find(t=>t.type==='video').segments.length,2);
  const index=readJson(f.indexFile).value;assert.equal(index.all_draft_store[0].tm_duration,30000000);assert.equal(index.all_draft_store[1].tm_duration,12);
}));
test('draft_info Mac + miroir synchronisés',()=>withFixture({mac:true,mirror:true},f=>{const e=engine(f),r=e.preview(f.project,{});assert.equal(e.commit(r.token).files,4);assert(fs.readFileSync(f.draftFile).equals(fs.readFileSync(f.mirrorFile)));}));
test('miroirs divergents bloqués',()=>withFixture({mirror:true},f=>{f.write(f.mirrorFile,{...f.raw,duration:12});error(()=>prepare(f.root,f.project),'MIRROR_DIVERGED');}));
test('timeline remplie refusée sans modification',()=>withFixture({},f=>{f.raw.tracks=[{type:'video',segments:[{id:'existing'}]}];f.write(f.draftFile,f.raw);const b=fs.readFileSync(f.draftFile);error(()=>prepare(f.root,f.project),'NONEMPTY_TIMELINE');assert(fs.readFileSync(f.draftFile).equals(b));}));
test('image + vidéo restent présentes',()=>withFixture({visuals:['001.png','002.mp4'],totalUs:10000000},f=>{const r=prepare(f.root,f.project);assert.deepEqual(r.report.rows.map(x=>x.type),['photo','video']);assert.equal(r.report.clips,2);assert.equal(r.draft.tracks.at(-2).segments.length,2);}));
test('video 8s pour 60s : refus puis répétition explicite',()=>withFixture({visuals:['001.mp4'],totalUs:60000000},f=>{error(()=>prepare(f.root,f.project),'VIDEO_TOO_SHORT');const r=prepare(f.root,f.project,{videoPolicy:'repeat',motion:'alternate'});assert.equal(r.report.clips,8);const s=r.draft.tracks.at(-2).segments;assert(s.every(x=>x.source_timerange.duration<=8000000));for(let i=1;i<s.length;i++)assert.equal(s[i-1].common_keyframes[0].keyframe_list[1].values[0],s[i].common_keyframes[0].keyframe_list[0].values[0]);}));
test('plusieurs audios imposent un choix explicite',()=>withFixture({audioCount:2},f=>{error(()=>prepare(f.root,f.project),'AUDIO_SELECT');const p=prepare(f.root,f.project,{audioPath:f.items.at(-1).file_Path});assert.equal(p.report.audio,'voice-1.wav');assert.equal(p.draft.tracks.filter(t=>t.type==='audio').length,1);assert(p.report.warnings.some(x=>x.includes('autres audios')));}));
test('média absent bloque avant toute écriture',()=>withFixture({},f=>{fs.unlinkSync(f.items[0].file_Path);error(()=>prepare(f.root,f.project),'MEDIA_MISSING');assert.equal(readJson(f.draftFile).value.duration,0);}));
test('média vide refusé',()=>withFixture({},f=>{fs.writeFileSync(f.items[0].file_Path,'');error(()=>prepare(f.root,f.project),'MEDIA_FILE');}));
test('durée audio absente refusée',()=>withFixture({},f=>{f.meta.draft_materials[0].value.at(-1).duration=0;f.write(f.metaFile,f.meta);error(()=>prepare(f.root,f.project),'AUDIO_DURATION');}));
test('projet changé après aperçu : aucune écriture',()=>withFixture({},f=>{const e=engine(f),r=e.preview(f.project,{});f.write(f.draftFile,{...f.raw,duration:1});error(()=>e.commit(r.token),'PROJECT_CHANGED');assert.equal(readJson(f.metaFile).value.tm_duration,0);}));
test('média changé après aperçu : aucune écriture',()=>withFixture({},f=>{const e=engine(f),r=e.preview(f.project,{});fs.appendFileSync(f.items[0].file_Path,'changed');error(()=>e.commit(r.token),'MEDIA_CHANGED');assert.equal(readJson(f.draftFile).value.duration,0);}));
test('modification Timelines/project.json invalide l’aperçu',()=>withFixture({mirror:true},f=>{const e=engine(f),r=e.preview(f.project,{});f.write(path.join(f.project,'Timelines','project.json'),{main_timeline_id:'OTHER'});error(()=>e.commit(r.token),'PROJECT_CHANGED');}));
test('restauration byte pour byte des trois fichiers',()=>withFixture({},f=>{const files=[f.draftFile,f.metaFile,f.indexFile];const before=files.map(x=>fs.readFileSync(x));const e=engine(f),r=e.preview(f.project,{}),done=e.commit(r.token);assert(e.restore(done.backupId).restored);files.forEach((x,i)=>assert(fs.readFileSync(x).equals(before[i])));}));
test('restauration protège les changements ultérieurs de CapCut',()=>withFixture({},f=>{const e=engine(f),r=e.preview(f.project,{}),done=e.commit(r.token);f.write(f.draftFile,{...readJson(f.draftFile).value,modified_by_capcut:true});error(()=>e.restore(done.backupId),'RESTORE_CONFLICT');assert(readJson(f.draftFile).value.modified_by_capcut);}));
test('index ambigu refusé',()=>withFixture({},f=>{const j=readJson(f.indexFile).value;j.all_draft_store.push({...j.all_draft_store[0]});f.write(f.indexFile,j);error(()=>prepare(f.root,f.project),'INDEX_MATCH');}));
test('catalogue de transitions lit les projets Mac',()=>withFixture({mac:true},f=>{const resource=path.join(f.temp,'transition');fs.mkdirSync(resource);f.raw.materials.transitions=[{id:'T',effect_id:'E',name:'Fade',path:resource}];f.write(f.draftFile,f.raw);const c=catalog(f.root);assert.equal(c.length,1);assert(c[0].available);}));
test('transitions absentes ou ressources manquantes refusées',()=>withFixture({},f=>{error(()=>prepare(f.root,f.project,{transitionIds:['missing']}),'TRANSITION_RESOURCE');f.raw.materials.transitions=[{id:'T',effect_id:'E',path:'/missing-resource'}];f.write(f.draftFile,f.raw);assert.equal(catalog(f.root)[0].available,false);error(()=>prepare(f.root,f.project,{transitionIds:['E']}),'TRANSITION_RESOURCE');}));
test('transitions uniquement aux frontières des scènes répétées',()=>withFixture({visuals:['001.mp4','002.mp4'],totalUs:60000000},f=>{const resource=path.join(f.temp,'transition');fs.mkdirSync(resource);f.raw.materials.transitions=[{id:'T',effect_id:'E',name:'Fade',path:resource,duration:500000}];f.write(f.draftFile,f.raw);const p=prepare(f.root,f.project,{videoPolicy:'repeat',transitionIds:['E']});assert.equal(p.draft.materials.transitions.length,2);const newly=p.draft.materials.transitions[1].id;const segs=p.draft.tracks.at(-2).segments;assert.equal(segs.filter(s=>s.extra_material_refs.includes(newly)).length,1);}));
test('ne réutilise pas un aperçu déjà consommé',()=>withFixture({},f=>{const e=engine(f),r=e.preview(f.project,{});e.commit(r.token);error(()=>e.commit(r.token),'PREVIEW_REQUIRED');}));
test('écriture refusée si CapCut ouvert',()=>withFixture({},f=>{const e=new Engine({root:f.root,backupDir:f.backupDir,guard:()=>{throw Object.assign(new Error('CapCut ouvert'),{code:'CAPCUT_OPEN'})}});const r=e.preview(f.project,{});error(()=>e.commit(r.token),'CAPCUT_OPEN');assert.equal(readJson(f.draftFile).value.duration,0);}));
test('projet lié ou extérieur refusé',()=>withFixture({},f=>{const link=path.join(f.root,'linked');fs.symlinkSync(f.project,link);error(()=>loadProject(f.root,link),'PROJECT_PATH');error(()=>loadProject(f.root,f.temp),'PROJECT_PATH');}));
test('plateforme non Mac : statut inconnu bloquant',()=>error(()=>capcutState('linux'),'PLATFORM'));
test('alias du dossier parent accepté ; lien du projet toujours refusé',()=>withFixture({},f=>{
  const alias=path.join(f.temp,'projects-alias');fs.symlinkSync(f.root,alias);
  const aliasProject=path.join(alias,path.basename(f.project));
  const e=new Engine({root:alias,backupDir:f.backupDir,guard:()=>{}});
  assert.equal(e.inspect(aliasProject).path,f.project);
  const preview=e.preview(aliasProject,{});e.commit(preview.token);
  assert.equal(readJson(f.draftFile).value.duration,30000000);
  const linked=path.join(f.root,'linked');fs.symlinkSync(f.project,linked);
  error(()=>loadProject(alias,linked),'PROJECT_PATH');
}));
