const { contextBridge, ipcRenderer } = require('electron');
const call = channel => value => ipcRenderer.invoke(channel, value);
contextBridge.exposeInMainWorld('elpo', {
  status: call('elpo:status'),
  chooseRoot: call('elpo:chooseRoot'),
  chooseFlowFolder: call('elpo:chooseFlowFolder'),
  clearFlowFolder: call('elpo:clearFlowFolder'),
  engine: (action, args) => ipcRenderer.invoke('elpo:engine', { action, args }),
  overview: call('elpo:overview'),
  mediaSources: call('elpo:mediaSources'),
  waveform: call('elpo:waveform'),
  loadFile: call('elpo:loadFile'),
  subtitles: call('elpo:subtitles'),
  export: (name, text) => ipcRenderer.invoke('elpo:export', { name, text }),
  preferences: call('elpo:preferences'),
  styles: call('elpo:styles'),
  favorite: call('elpo:favorite'),
  openCapcut: call('elpo:openCapcut'),
  openBackups: call('elpo:openBackups'),
  ffmpeg: call('elpo:ffmpeg'),
  chooseDir: call('elpo:chooseDir'),
  exportSettings: call('elpo:exportSettings'),
  exportStart: call('elpo:exportStart'),
  exportCancel: call('elpo:exportCancel'),
  exportClear: call('elpo:exportClear'),
  jobs: call('elpo:jobs'),
  reveal: call('elpo:reveal'),
  pilotSettings: call('elpo:pilotSettings'),
  pilotAccess: call('elpo:pilotAccess'),
  pilotCalibrate: call('elpo:pilotCalibrate'),
  pilotStart: call('elpo:pilotStart'),
  pilotStop: call('elpo:pilotStop'),
  on: callback => { const listener = (_event, message) => callback(message); ipcRenderer.on('elpo:event', listener); return () => ipcRenderer.removeListener('elpo:event', listener); },
});
